export const AUTH_CREATE_SUCCESS = "AUTH_CREATE_SUCCESS";
export const AUTH_CREATE_FAILURE = "AUTH_CREATE_FAILURE";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const NEWS_ADD_SUCCESS = "NEWS_ADD_SUCCESS";
export const NEWS_ADD_FAILURE = "NEWS_ADD_FAILURE";