export const AUTH_CREATE_SUCCESS = "AUTH_CREATE_SUCCESS";
export const AUTH_CREATE_FAILURE = "AUTH_CREATE_FAILURE";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_ALL_MEDIA_ADMIN = "GET_ALL_MEDIA_ADMIN";
export const LOADER_ACTION = "LOADER_ACTION";
export const All_LATEST_NEWS = "All_LATEST_NEWS";
